esphome:
  name: "mitch_personal-status-display"
  friendly_name: "Mitch's Personal Status Display"
  on_boot:
    priority: 600
    then:
      - delay: 1s
      - if:
          condition:
            or:
              - lvgl.page.is_showing: page_screensaver
              - lvgl.is_paused
              - light.is_off: light_backlight
          then:
            - light.turn_on: light_backlight
            - lvgl.resume
            - lvgl.page.show: page_main
      - script.execute: update_display

<<: !include includes/constants.yaml
<<: !include includes/hardware.yaml
<<: !include includes/fonts.yaml
<<: !include includes/ui.yaml
<<: !include includes/logic.yaml

api:
  encryption:
    key: !secret api_encryption_key

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret ota_password