substitutions:
  display_w: 240
  display_h: 320
  idle_timeout: 5s
  
  # Colors (hex codes)
  color_home: "0xADD8E6"  # Light blue
  color_sleeping: "0x800080"  # Purple
  color_working: "0xFFFF00"  # Yellow
  color_gaming: "0x00FF00"  # Green
  color_meeting: "0xFF0000"  # Red
  color_busy: "0xFF0000"  # Red (same as meeting)
  color_away: "0xFFFFFF"  # White
  
  # Icons (Unicode)
  icon_home: "\U0000e587"
  icon_sleeping: "\U0000f174"
  icon_working: "\U0000e8f9"
  icon_gaming: "\U0000ea28"
  icon_meeting: "\U0000e9a5"
  icon_busy: "\U0000effb"
  icon_away: "\U0000e594"